openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: Authentication API documentation
servers:
  - url: http://localhost:4002
paths:
  /auth/signup:
    post:
      summary: User registration
      description: Register a new user in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
                surname:
                  type: string
                  example: Doe
                username:
                  type: string
                  example: johndoe
                email:
                  type: string
                  format: email
                  example: john@example.com
                password:
                  type: string
                  example: strongPassword123
      responses:
        "201":
          description: User created successfully
        "400":
          description: Validation failed
        "500":
          description: Internal server error

  /auth/verify:
    post:
      summary: Verify user account
      description: Verify user account using a verification code sent by email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "123456"
                email:
                  type: string
                  format: email
                  example: john@example.com
      responses:
        "200":
          description: User account verified successfully
        "400":
          description: Verification code invalid or expired
        "404":
          description: User not found

  /auth/signin:
    post:
      summary: User login
      description: Authenticate user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: strongPassword123
      responses:
        "200":
          description: Signin successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        "400":
          description: Missing or wrong credentials
        "403":
          description: Account not verified
        "404":
          description: User not found

  /auth/resend-verification:
    post:
      summary: Resend verification email
      description: Send a new verification code to the user email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: john@example.com
      responses:
        "200":
          description: New verification code sent
        "400":
          description: Email not provided
        "404":
          description: User not found
        "500":
          description: Internal server error

  /auth/user:
    get:
      summary: Get authenticated user info
      description: Return user profile information
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User info retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      surname:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
        "401":
          description: Unauthorized

  /auth/forgot-password:
    post:
      summary: Request password reset
      description: Send password reset email with token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: john@example.com
      responses:
        "200":
          description: Reset email sent
        "400":
          description: User not found or email missing
        "500":
          description: Internal server error

  /auth/reset-password:
    post:
      summary: Reset user password
      description: Reset the user password using a valid token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "abc123token"
                password:
                  type: string
                  example: newStrongPassword123
      responses:
        "200":
          description: Password reset successfully
        "400":
          description: Invalid or expired token, or validation failed
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
